name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a front-end env file 
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          directory: .
          file_name: .env
          fail_on_empty: true 
      - name: Build
        run: docker-compose build
      - name: Run
        run: docker-compose down && docker-compose up -d